#pragma once

#define PLAYER_BASE 0x0067FBF8
#define GUILD_UNIFORM_OFFSET 0x9F4
#define CHARACTER_NAME_OFFSET 0x14
#define SOULID_OFFSET 0x04

#define GUILD_UNIFORM_LENGTH 6
#define CHARACTER_NAME_LENGTH 32